# Generated by Django 5.2.5 on 2025-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
