# Generated by Django 5.2.5 on 2025-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0002_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
