# Generated by Django 5.2.5 on 2025-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0003_alter_blog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="point",
            field=models.FloatField(null=True),
        ),
    ]
