# Generated by Django 5.2.5 on 2025-09-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0005_blog_slug_profile_blog_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "verbose_name": "Blog Yazısı",
                "verbose_name_plural": "Blog Yazıları",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profiller"},
        ),
        migrations.AddField(
            model_name="blog",
            name="published_at",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Taslak"),
                    ("published", "Yayınlandı"),
                    ("archived", "Arşivledni"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="RestAPI.profile",
                verbose_name="Yazar",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Yorum İçeriği")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="RestAPI.profile",
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="RestAPI.blog",
                        verbose_name="Blog Yazısı",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="RestAPI.comment",
                        verbose_name="Ana Yorum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yorum",
                "verbose_name_plural": "Yorumlar",
            },
        ),
    ]
