# Generated by Django 5.2.5 on 2025-09-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0006_alter_blog_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
