# Generated by Django 5.2.6 on 2025-12-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RestAPI", "0009_alter_comment_point_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="point",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tittle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Yorum İçeriği"),
        ),
    ]
